name: Pages

on: push

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: diplodoc-platform/docs-build-action@v2
        with:
          revision: "pr-${{ github.event.pull_request.number }}"
          src-root: "./docs"
          build-root: "github-pages"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: github-pages

  # Deploy job
  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action